# Generated by Django 3.0.6 on 2020-05-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post.png', upload_to='blog_img/%d%m%Y'),
        ),
    ]
