# Generated by Django 3.0.6 on 2020-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200527_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='class_name',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth'), ('Nineth', 'Nineth'), ('Tenth', 'Thenth'), ('Eleventh', 'Eleventh'), ('Twelveth', 'Twelveth'), ('All', 'All')], default='all', max_length=10),
        ),
    ]
